- hosts: all

  tasks:
    - name: install packages
      apt:
        pkg:
          - python3-docker
        state: latest
        update_cache: yes
      become: yes

    - name: run app
      docker_container:
        name: redmine
        image: redmine:4.2.1
        ports:
          - "{{ app_port }}:3000"

    - name: setup monitoring
      include_role:
        name: datadog.datadog
        apply:
          become: yes
      vars:
        datadog_api_key: "{{ datadog_token }}"
        datadog_site: "datadoghq.eu"
        datadog_checks:
          http_check:
            init_config:
            instances:
              - name: Application health check status
                url: http://localhost:{{ app_port }}
                timeout: 5
                method: GET
