- hosts: all

  tasks:
    - name: run app
      docker_container:
        name: redmine
        image: "{{ app_image }}"
        ports:
          - "{{ app_port }}:3000"
        env:
          REDMINE_DB_DATABASE: "{{ db_name }}"
          REDMINE_DB_POSTGRES: "{{ db_host }}"
          REDMINE_DB_PORT: "{{ db_port }}"
          REDMINE_DB_USERNAME: "{{ db_username }}"
          REDMINE_DB_PASSWORD: "{{ db_password }}"
